#include "characters.h"

const sf::Vector2u Characters::ghost_green_down{0, 0};
const sf::Vector2u Characters::ghost_green_up{1, 0};
const sf::Vector2u Characters::ghost_blue_down{2, 0};
const sf::Vector2u Characters::ghost_blue_up{3, 0};
const sf::Vector2u Characters::ghost_pink_down{4, 0};
const sf::Vector2u Characters::ghost_pink_up{5, 0};
const sf::Vector2u Characters::ghost_yellow_down{6, 0};
const sf::Vector2u Characters::ghost_yellow_up{7, 0};
const sf::Vector2u Characters::ghost_beige_down{0, 1};
const sf::Vector2u Characters::ghost_beige_up{1, 1};
const sf::Vector2u Characters::mine{8, 0};
const sf::Vector2u Characters::handle_opened{2, 1};
const sf::Vector2u Characters::handle_closed{3, 1};
const sf::Vector2u Characters::enemy_calm{4, 1};
const sf::Vector2u Characters::enemy_angry{5, 1};
const sf::Vector2u Characters::drill{6, 1};
const sf::Vector2u Characters::driil_up{7, 1};
const sf::Vector2u Characters::drill_down{8, 1};
const sf::Vector2u Characters::friend_small{0, 2};
const sf::Vector2u Characters::friend_small_up{1, 2};
const sf::Vector2u Characters::friend_small_down{2, 2};
const sf::Vector2u Characters::friend_big{3, 2};
const sf::Vector2u Characters::friend_big_up{4, 2};
const sf::Vector2u Characters::friend_big_down{5, 2};
const sf::Vector2u Characters::bat_wing_up{6, 2};
const sf::Vector2u Characters::bat_wing_middle{7, 2};
const sf::Vector2u Characters::bat_wing_down{8, 2};